export const cities = [
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Belo Horizonte",
  "Manaus",
  "Curitiba",
  "Recife",
  "Porto Alegre",
  "Goiânia",
  "Belém",
  "Guarulhos",
  "Campinas",
  "São Luís",
  "São Gonçalo",
  "Maceió",
  "Duque de Caxias",
  "Nova Iguaçu",
  "Natal",
  "Teresina",
  "São Bernardo do Campo",
  "Campo Grande",
  "João Pessoa",
  "Santo André",
  "Osasco",
  "Jaboatão dos Guararapes",
  "Contagem",
  "São José dos Campos",
  "Uberlândia",
  "Sorocaba",
  "Ribeirão Preto",
  "Niterói",
  "Belford Roxo",
  "Cuiabá",
  "Aracaju",
  "Feira de Santana",
  "Joinville",
  "Londrina",
  "Juiz de Fora",
  "Serra",
  "Mossoró",
  "Caxias do Sul",
  "Pelotas",
  "Campos dos Goytacazes",
  "Vila Velha",
  "Betim",
  "Montes Claros",
  "Blumenau",
  "Macapá",
  "Rio Branco",
  "Boa Vista",
  "Palmas",
  "Porto Velho",
  "Vitória",
  "Florianópolis",
  "Marabá",
  "Ananindeua",
  "Maringá",
  "Canoas",
  "Cascavel",
  "Bauru",
  "Pelotas",
  "Itaquaquecetuba",
  "Itaboraí",
  "Parauapebas",
  "Ponta Grossa",
  "Taubaté",
  "Divinópolis",
  "Piracicaba",
  "Santa Maria",
  "Limeira",
  "Cubatão",
  "Araraquara",
  "São José do Rio Preto",
  "Várzea Grande",
  "Barueri",
  "Juazeiro do Norte",
  "Castanhal",
  "Marília",
  "Francisco Morato",
  "Tatuí",
  "Mogi das Cruzes",
  "Guarujá",
  "Itu",
  "Santa Luzia",
  "Itabuna",
  "Mauá",
  "Barra Mansa",
  "Cariacica",
  "Santana de Parnaíba",
  "Colombo",
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "San Francisco",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Nashville",
  "Detroit",
  "Oklahoma City",
  "Portland",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Mesa",
  "Sacramento",
  "Atlanta",
  "Kansas City",
  "Colorado Springs",
  "Miami",
  "Raleigh",
  "Omaha",
  "Long Beach",
  "Virginia Beach",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Arlington",
  "New Orleans",
  "Wichita",
  "Cleveland",
  "Tampa",
  "Bakersfield",
  "Aurora",
  "Honolulu",
  "Anaheim",
  "Santa Ana",
  "Corpus Christi",
  "Riverside",
  "Lexington",
  "St. Louis",
  "Stockton",
  "Pittsburgh",
  "Saint Paul",
  "Cincinnati",
  "Anchorage",
  "Henderson",
  "Greensboro",
  "Plano",
  "Newark",
  "Lincoln",
  "Toledo",
  "Orlando",
  "Chula Vista",
  "Irvine",
  "Fort Wayne",
  "Jersey City",
  "Durham",
  "St. Petersburg",
  "Laredo",
  "Buffalo",
  "Madison",
  "Lubbock",
  "Chandler",
  "Scottsdale",
  "Glendale",
  "Reno",
  "Norfolk",
  "Winston–Salem",
  "North Las Vegas",
  "Irving",
  "Chesapeake",
  "Gilbert",
  "Hialeah",
  "Garland",
  "Fremont",
  "Richmond",
  "Boise",
  "Baton Rouge",
  "London",
  "Birmingham",
  "Glasgow",
  "Liverpool",
  "Bristol",
  "Manchester",
  "Sheffield",
  "Leeds",
  "Edinburgh",
  "Leicester",
  "Coventry",
  "Bradford",
  "Cardiff",
  "Belfast",
  "Nottingham",
  "Newcastle upon Tyne",
  "Hull",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Derby",
  "Sunderland",
  "Southampton",
  "Portsmouth",
  "Brighton",
  "Plymouth",
  "Milton Keynes",
  "Aberdeen",
  "Luton",
  "Oxford",
  "Cambridge",
  "Reading",
  "Norwich",
  "Swindon",
  "Exeter",
  "York",
  "Carlisle",
  "Lancaster",
  "Bath",
  "Canterbury",
  "Durham",
  "Chester",
  "Winchester"
];